# Generated by Django 3.1.4 on 2020-12-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='test',
        ),
    ]
